[package]
name = "chemistry"
version = "0.1.0"
edition = "2021"

[dependencies]
termion = "4.0.3"
json = "*"
textwrap = "*"
itertools = "0.13.0"
phf = { version = "0.11.2", features = ["macros"] }
clap = { version = "4.5.20", features = ["derive"] }
